[general]
  case = "plugin_example2"
[general.plugin_registry.plugins]
  plugin_example = "../DE330_Training_2024/Exercises/Develop/Simple_plugin"
[suite_control]
  suite_definition = "ExampleSuiteDefinition"

[submission.tasks.plugin_example_group]
  INTERPRETER = "/usr/bin/bash"
  SCHOST = "hpc"                             # Refers to the submission group in troika
  tasks = ["Bashtask"]
  WRAPPER = ""

[submission.types.plugin_example_group.BATCH]
  NAME = "#SBATCH --job-name=@TASK_NAME@"
  NODES = "#SBATCH --nodes=1"
  NTASKS = "#SBATCH --ntasks=1"
  QOS = "#SBATCH --qos=np"
  WALLTIME = "#SBATCH --time=00:05:00"

[submission.types.plugin_example_group.ENV]
  DEODE = "awesome"

[submission.types.plugin_example_group.MODULES]
  ECFLOW = ["load", "ecflow"]

